# Generated by Django 3.1.3 on 2020-12-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mes',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='mes',
            old_name='des',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='mes',
            old_name='dis',
            new_name='Distance',
        ),
        migrations.RenameField(
            model_name='mes',
            old_name='location',
            new_name='Location',
        ),
    ]
