# Generated by Django 3.1.3 on 2020-12-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20201205_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='Location',
            field=models.CharField(blank=True, default='Ghaziabad', max_length=200),
        ),
    ]
