# Generated by Django 3.1.3 on 2020-12-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20201207_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='Location',
            field=models.CharField(default='Ghaziabad', max_length=200),
        ),
    ]
